### PR TITLE
Ban openssl crates

### PR DESCRIPTION
**Pull request by kim**
We don't want any openssl, because a. its license is not GPL-compatible
(even though the crates are licensed differently), and b. we need a
tight grip on what crypto we pull in.

### CODE REVIEW

**Comment by kim** [comment]
Nb. `upstream` will likely need to review the features config for their `git2` dependency -- if `default-features` is enabled there, it will pull in `openssl-*` through the direct dep.

**Comment by xla** [comment]
> Nb. `upstream` will likely need to review the features config for their `git2` dependency -- if `default-features` is enabled there, it will pull in `openssl-*` through the direct dep.

I believe Upstream depends on `git2` transitively through librad/surf.

**Review by xla — APPROVED** [review]
🔘 ➖ 📚 🏋

**Comment by kim** [comment]
> I believe Upstream depends on `git2` transitively through librad/surf.

Ya seems so. I was convinced it needed at least a dev-dependency.

**Comment by kim** [comment]
Closed via c29aa348b34addf148be0d0c328d35a4f887a3f9

**Pull request closed without merging**
