### PR TITLE
rad-clib: rename directory from clib to rad-clib

### PR DESCRIPTION
**Pull request by FintanH**
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>

### CODE REVIEW

**Comment by kim** [comment]
Bikeshed: iirc, we said `link-` is protocol-related, `rad-` is CLI (and perhaps
other executables) related, and `cob-` might be the prefix for collaborative
objects. So is `clib` not rather `rad-clib`?

**Comment by FintanH** [comment]
> Bikeshed

Thanks! Should be the correct colour now :)

**Review by xla — DISMISSED** [review]
🗯 ☯ 😓 🔙

**Review by xla — APPROVED** [review]
🚍 🌫 🏖 🐂

**Review by alexjg — APPROVED** [review]

**Review by xla — APPROVED** [review]
💹 🐻 🌖 🎮

**Pull request merged**
