### PR TITLE
git: prune non-conforming references in `fetched_peers

### LINKED ISSUE #500: Pruning in fetched_peers
In https://github.com/radicle-dev/radicle-link/pull/478/files#diff-fe1d1a45efacfdf43a7b387a93ab0db0b6eeab3e68b613e5f190fcbcdafb6ff0R772-R799 we introduced parsing `fetched_peers` when we perform a shotgun fetch for a first time `replicate`. If there was an error in parsing then we `continue`, but this leaves the non-conforming reference lying around. It would be better to attempt to `prune` the reference.

### PR DESCRIPTION
**Pull request by therealyingtong**
Closes #500.

### CODE REVIEW

**Review by xla — COMMENTED** [review]
utACK

⛱ 👐 🌼 🌃

**Comment by FintanH** [comment]
Thanks for jumping in on this @therealyingtong. I'm not sure if this change might be necessary as we're going to revisit the replication. However, @kim might have a better idea about what the plan is there.

**Comment by kim** [comment]
tbh, I stared at this a few times, but couldn't fully understand if it makes sense... so much for "needs to be revisited"

**Comment by FintanH** [comment]
> tbh, I stared at this a few times, but couldn't fully understand if it makes sense... so much for "needs to be revisited"

:sweat_smile: 

So the issue the `FIXME` wants to prevent is that `PeekAll` fetches a wildcard for remotes, and we try and parse the peer in this call. However, it couldn't parse then we shouldn't really keep the reference around, and rather prune it. 

But actually, as usual, I jumped the gun and I'm realising this change doesn't necessarily do that. It just removes them from the updated tips.

I think `PeekAll` is more trouble than it's worth...

**Comment by FintanH** [comment]
Thanks for the PR @therealyingtong, but I'm going to close this as we're revisiting the implementation of replication soon. Thanks for your time :bow:

**Pull request closed without merging**
