### PR TITLE
Lockless cargo

### PR DESCRIPTION
**Pull request by kim**
Tries out approach 1 of #307 to see what happens.

Findings so far:

* [SemVer is a lie](https://blog.illicitonion.com/rust-minimum-versions-semver-is-a-lie/) (yeah, I tried `-Z minimal-versions`)
* It is not clear when cargo decides to pick a different version for a workspace crate (even with relaxed constraints)

### CODE REVIEW

**Comment by kim** [comment]
This should win me an award:

image

**Comment by FintanH** [comment]
I wanna see those 19 lines gone too

**Comment by kim** [comment]
Alright, I'd like to see us roll lockless. We have the `radicle-bins` repo, which is supposedly going to have a `Cargo.lock`, and this branch already caught a diverging version constraint in the sub-crates.

I also think that we should employ a more lenient versioning policy (ie. no upper bounds where possible), but I'll leave that for another time.

**Review by xla — DISMISSED** [review]
👒 ☠ 🔚 🎆

**Pull request merged**
