### PR TITLE
RFC: Standardise on AsciiDoc instead of Markdown

### PR DESCRIPTION
**Pull request by kim**
[Rendered](https://github.com/radicle-dev/radicle-link/blob/rfc/asciidoc/docs/rfc/0000-asciidoc.adoc)

### CODE REVIEW

**Review by alexjg — APPROVED** [review]

**Review by FintanH — APPROVED** [review]
AsciiDoc seems nicer from a glance :+1: I've only heard bad things about rst

**Comment by kim** [comment]
> "reStructuredText" is ONE word, not two!

And if you do not indent it by 2 tabs (**not** 4 spaces!), it won't compile
either. qed.

**Comment by kim** [comment]
@xla do you have an opinion?

**Review by xla — DISMISSED** [review]
☄ 🏃 🆙 🕜

> @xla do you have an opinion?

JUST DO IT

**Pull request merged**
