### PR TITLE
net: Fix rustdoc links

### PR DESCRIPTION
**Pull request by kim**
Signed-off-by: Kim Altintop <kim@monadic.xyz>

### CODE REVIEW

**Comment by kim** [comment]
I there some trick to make these compile errors, but avoid the whole pedantic you haven't put a comment on this struct field stuff? @xla?

**Comment by xla** [comment]
> I there some trick to make these compile errors, but avoid the whole pedantic you haven't put a comment on this struct field stuff? @xla?

Could it be that this is what you after: https://github.com/radicle-dev/radicle-registry/blob/00436dc9b2fad0ad96c2e562f76873d0aa21a2c0/ci/run#L69-L70

**Review by xla — APPROVED** [review]
🔢 😸 📘 🐞

**Review by FintanH — APPROVED** [review]
Lovely :ok_hand:

**Pull request merged**
