### PR TITLE
Specify URNs

### PR DESCRIPTION
**Pull request by kim**
Thanks @rudolfs for beating me to it!

### CODE REVIEW

**Review by FintanH — APPROVED** [review]
:kissing::metal:

**Comment by rudolfs** [comment]
> Thanks @rudolfs for beating me to it!

Ya, #355 was supposed to just be a starting point & incentive : P

**Comment by rudolfs** [comment]
I know that there is not supposed to be a distinction between projects and users, but in practice those are the only entities that can be addressed at the moment, would be nice to mention that somehow. Maybe in the examples section?

**Review by rudolfs — APPROVED** [review]

**Comment by kim** [comment]
> there is not supposed to be a distinction between projects and users

The difference is specified in [Delegations](https://github.com/radicle-dev/radicle-link/blob/3a593a1a11398830f0da2f877a10d2303de1f380/docs/spec/identities.md#delegations), but it is not relevant for describing what the format of a URN is. Because, you don't know what you'll get when resolving a URN!

I agree that this is rather awkward, and I've proposed in the past to include the _kind_ of identity (content-type, if you wish) a URN is supposed to resolve to in the URN itself. The counter-argument is that you have to deal with the situation that there is a mismatch _in any case_ -- it is validated only after the fact, so technically it would even be possible to change the type if there are enough signers.

**Pull request merged**
