### PR TITLE
net: run rere after serving the fetch

### PR DESCRIPTION
**Pull request by kim**
Running both concurrently makes things harder to reason about. Better
opportunities for optimisation and interleaving may arise with git
protocol v2.

Signed-off-by: Kim Altintop <kim@monadic.xyz>

### CODE REVIEW

**Review by xla — APPROVED** [review]
Bikeshed: debug could be more appropriate for the rere logs.

ℹ️ 🚑 👊 ⭐️

**Review by FintanH — APPROVED** [review]
This will also limit the case where we see history rewrites since `rere` won't go before the replication :)

**Comment by xla** [comment]
> This will also limit the case where we see history rewrites since `rere` won't go before the replication :)

Does that not still depend on respecting the force flag as addressed in libgit2/libgit2#5854

**Comment by FintanH** [comment]
> Does that not still depend on respecting the force flag as addressed in libgit2/libgit2#5854

Not necessarily. Emphasis on the word _limit_. We were running into the issue because the seed would `rere` _before_ `replicate` and we would witness the rewrite. Since we're enforcing `replicate` goes before `rere` here it means that the history will be preserved. But it doesn't rule out _all_ history rewrites, of course.

**Review by FintanH — APPROVED** [review]

**Pull request merged**
