### PR TITLE
net: use stateless retry

### PR DESCRIPTION
**Pull request by kim**
Popped off the reading list: QUIC stateless retry is essentially a
defense against UDP reflection attacks, adding one (small) roundtrip to
the handshake.

Signed-off-by: Kim Altintop <kim@monadic.xyz>

### CODE REVIEW

**Review by FintanH — COMMENTED** [review]
I'm finding it hard to understand the section linked. Is the idea that the server knows how to retry packets without doing the cryptographic handshake again? Or am I off the mark?

**Comment by kim** [comment]
It's about requiring the initiator (client) to verify its network address: the client sends `ClientHello`, but instead of a large-ish `ServerHello`, the server sends a small retry token which the client cannot guess, and doesn't commit to any handshake state yet. The client must echo this token back, and so the server can verify that the source address tuple is indeed owned by the client.

Remember that it is very easy to spoof the source address in UDP, which can be used to trick the receiver into sending the response to an innocent third machine. A classic DoS attack.

**Comment by FintanH** [comment]
> It's about requiring the initiator (client) to verify its network address: the client sends ClientHello, but instead of a large-ish ServerHello, the server sends a small retry token which the client cannot guess, and doesn't commit to any handshake state yet. The client must echo this token back, and so the server can verify that the source address tuple is indeed owned by the client.

Ah, that's _WAY_ more clearer :smile: 

> Remember that it is very easy to spoof the source address in UDP, which can be used to trick the receiver into sending the response to an innocent third machine. A classic DoS attack.

So it'd be like `A` asks for a large project from `B` but then `A` malevolently puts `C`'s address in as the one `B` should respond to?

**Comment by FintanH** [comment]
Looking up "reflection attack" helped :) Should have done that first!

**Review by FintanH — APPROVED** [review]

**Comment by FintanH** [comment]
> Looking up "reflection attack" helped :) Should have done that first!

For anyone else who might be unfamiliar, the start of this is a good primer https://blog.cloudflare.com/reflections-on-reflections/

**Comment by kim** [comment]
> large project

I don't think this would be possible. To get past the handshake, the client must own the source address. QUIC doesn't allow to change the source address midway without going through a connection migration protocol (which has pretty much the same purpose).

Stateless retry happens _before_ the handshake, so the payload in a reflection attack would be the `ServerHello` (which is not nothing).

**Comment by FintanH** [comment]
> Stateless retry happens before the handshake, so the payload in a reflection attack would be the ServerHello (which is not nothing).

Right, after reading up on it the amplification seems to come from asking more than 1 server to respond to the victim

**Comment by kim** [comment]
Can someone repro the test failure (`smoke::gossip::fetches_on_gossip_notify`) locally? I'd be surprised if it would be related to the change.

**Comment by kim** [comment]
Ah nevermind. I think _someone_ was lazy and thought they'd could get away without minute `spawn_blocking`.

**Review by xla — DISMISSED** [review]
🌎 🕚 ❄️ 🔋

**Review by FintanH — DISMISSED** [review]

**Pull request merged**
