### PR TITLE
Adds 'libiconv' to Nix shell

### PR DESCRIPTION
**Pull request by jkachmar**
I tried building this repository on macOS for the first time and I ran into a compilation error when building the 
`libgit2-sys` crate:

<details>
<summary>Cargo Error Log Snippet</summary>
<p>

```
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = Some("clang")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=x86_64-apple-darwin" "-I" "/Users/jkachmar/src/radicle-link/target/debug/build/libgit2-sys-bec8595a366d44df/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/Users/jkachmar/src/radicle-link/target/debug/build/libz-sys-c4af3bc80a8004b2/out/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/Users/jkachmar/src/radicle-link/target/debug/build/libgit2-sys-bec8595a366d44df/out/build/libgit2/src/commit_list.o" "-c" "libgit2/src/commit_list.c"
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=x86_64-apple-darwin" "-I" "/Users/jkachmar/src/radicle-link/target/debug/build/libgit2-sys-bec8595a366d44df/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/Users/jkachmar/src/radicle-link/target/debug/build/libz-sys-c4af3bc80a8004b2/out/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/Users/jkachmar/src/radicle-link/target/debug/build/libgit2-sys-bec8595a366d44df/out/build/libgit2/src/merge_driver.o" "-c" "libgit2/src/merge_driver.c"
cargo:warning=In file included from libgit2/src/commit_list.c:12:
cargo:warning=In file included from libgit2/src/odb.h:19:
cargo:warning=In file included from libgit2/src/filter.h:12:
cargo:warning=In file included from libgit2/src/attr_file.h:17:
cargo:warning=In file included from libgit2/src/futils.h:14:
cargo:warning=libgit2/src/path.h:430:10: fatal error: 'iconv.h' file not found
cargo:warning=#include <iconv.h>
cargo:warning=         ^~~~~~~~~
cargo:warning=1 error generated.
cargo:warning=In file included from libgit2/src/merge_driver.c:12:
cargo:warning=In file included from libgit2/src/merge.h:15:
cargo:warning=In file included from libgit2/src/iterator.h:15:
cargo:warning=In file included from libgit2/src/ignore.h:12:
cargo:warning=In file included from libgit2/src/repository.h:24:
cargo:warning=In file included from libgit2/src/attrcache.h:12:
cargo:warning=In file included from libgit2/src/attr_file.h:17:
cargo:warning=In file included from libgit2/src/futils.h:14:
cargo:warning=libgit2/src/path.h:430:10: fatal error: 'iconv.h' file not found
cargo:warning=#include <iconv.h>
cargo:warning=         ^~~~~~~~~
exit code: 1
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=x86_64-apple-darwin" "-I" "/Users/jkachmar/src/radicle-link/target/debug/build/libgit2-sys-bec8595a366d44df/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/Users/jkachmar/src/radicle-link/target/debug/build/libz-sys-c4af3bc80a8004b2/out/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/Users/jkachmar/src/radicle-link/target/debug/build/libgit2-sys-bec8595a366d44df/out/build/libgit2/src/proxy.o" "-c" "libgit2/src/proxy.c"
cargo:warning=1 error generated.
exit code: 1
```

</details>
</p>

After I added `libiconv` to Nix shell's `buildInputs` everything seemed to compile just fine (at least as far as `cargo watch -c` is concerned, I haven't tested anything more than that yet).

### CODE REVIEW

**Comment by jkachmar** [comment]
I also found it useful to add `cargo-watch` to `buildInputs`, since I don't have `cargo` installed locally otherwise and it did make poking around the project a bit more convenient.

I can add it to this PR if you think that might be helpful, but I wasn't sure how much of the development environment was meant to be managed here versus directly by the developers on their machine.

**Comment by kim** [comment]
That's actually quite interesting, the libgit2 bindings configure libgit2 with iconv _only on macos_:

**Comment by FintanH** [comment]
@jkachmar ya since I'm purely using this for development `cargo-watch` seems like a reasonable addition.

And you didn't see any funny business with `cargo watch -c` constantly reloading from `libz-sys` onwards?

I think I'll test out working without the `shellHook` portion today and see if anything goes wrong. It seems to be the culprit and I cribbed it from somewhere to initially get things working :thinking:

**Comment by jkachmar** [comment]
@kim I did a little digging and it looks like this explains why `libgit2` depends on `libiconv` for macOS:

https://github.com/libgit2/libgit2/pull/1886

Historically it looks like that bit of configuration in the Rust library was carried through from the old CMake build, which I’m assuming was informed by the `libgit2` CMake stuff.

@FintanH I didn’t have any issues reloading `libz-sys`, but my _guess_ was going to be that adding `zlib.dev` might help. From what I can tell the LLVM path stuff seems like it’s used when/if you’re doing `cbindgen` stuff?

Not 100% sure, though; I could try testing this out on a NixOS machine if you think that could help though.

**Comment by FintanH** [comment]
> Not 100% sure, though; I could try testing this out on a NixOS machine if you think that could help though.

If you have access to one :thinking: But `zlib.dev` didn't help for me. We can just merge this once you've updated master :+1:

**Comment by jkachmar** [comment]
Some (small) additional changes have snuck in now, in order:

- a6fc706 scoped `with pkgs` a bit more tightly (so it only applies to the `buildInputs` package list
  - I've picked this up as a personal "best practice" with Nix just because it means that you're only importing _everything_ in the `pkgs` namespace for a very contained scope, but i can revert this if you feel otherwise
- 6653bc8 added `cargo-watch`
  - it might be useful to note that this is coming from `<nixpkgs>`, which means the version of `cargo-watch` might lag behind what's on [crates.io](https://www.crates.io)
- 98b5b40 added `cacert`
  - this isn't strictly necessary I guess, but `cargo` needs valid a valid SSL cert store in order to download dependencies and build the project; normally the OS provides this so you're fine, but if you enter into a Nix shell with `nix-shell --pure` that gets sandboxed away

---

@FintanH I tested this on a NixOS machine (20.03 release train, slightly dated package set) and haven't had any problems with `libz-sys` recompilation stuff when running `cargo watch -c`.

**Review by FintanH — APPROVED** [review]
Sweet, thanks for the breakdown @jkachmar! Appreciate your help here and passing on some knowledge :grin: 

I'm still seeing the libz-sys reloading. Must be something to do with my setup :thinking:

**Comment by kim** [comment]
@FintanH are we going to merge this?

**Comment by FintanH** [comment]
> @FintanH are we going to merge this?

I think we can close this. I've been on the lookout for a better Rust development setup, for example, using something like this https://github.com/oxalica/rust-overlay. I'm actually using something different than this `default.nix` at the moment.

 Thanks for the help @jkachmar :blush:

**Pull request closed without merging**
