### PR TITLE
Make RadUrn identified by Hash instead of Multihash

### PR DESCRIPTION
**Pull request by kim**
Note that `Hash` is not forward-compatible, ie. an earlier version of the software will refuse to handle a hash algorithm introduced later. Perhaps this is what @massimiliano-mantione's doubts were. 

I don't have a good solution for how to solve this, since we assume that we must stay compatible with `registry`. I am, otoh, also not sure where this requirement came from, respectively what hash the `registry` wants to verify, and based on which input data.

### CODE REVIEW

**Comment by geigerzaehler** [comment]
I’m also not aware of any requirements on the hash from the registry. The registry considers data from the registry opaque at the moment and there are now plans to change this. We just provide some blob storage for projects and the app determines how to encode coco data and store it.

**Comment by FintanH** [comment]
> I don't have a good solution for how to solve this

```Error: please upgrade `librad`, thank you.```

**Comment by cloudhead** [comment]
In the future, we will want to consolidate the TUF verification such that it can be performed both in the registry, and offline, in `radicle-link`. This will ensure that similar functionality (multi-sig project metadata updates) isn't duplicated with different semantics, and will also allow the registry to operate as a trusted project metadata/identity verifier. For this to work though, the registry needs to be able to run the same code as radicle-link, namely the hashing function and signature verification.

This will come about when we start allowing users to anchor project metadata state on the registry.

**Comment by kim** [comment]
@cloudhead Well, for it to work, the entire history of an identity branch must be stored on-chain. Or, a full-node acts as a radicle-link node, in which case the actual verification is not an on-chain computation.

Anyways, I'll leave it like this for now, but add a follow-up ticket to accept _any_ multihash when deserialising.

**Pull request merged**
